version: 2
updates:
  # Maintain npm / pnpm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5

  # Maintain GitHub Actions workflow dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
